### ISSUE TITLE
Create website favicon

### ISSUE THREAD

**Issue by Lithl** [Lithl/challenge32#11]
We need a favicon for the website! Design may or may not be related to logo created for #10

**Comment by Elonex777** [comment]
16x16 size:
![favicon 16x16](https://user-images.githubusercontent.com/44607543/83105152-66f64c00-a0ba-11ea-91eb-3690e6aca311.png)

original size if one day you need it:
![favicon-512x512](https://user-images.githubusercontent.com/44607543/83106033-0bc55900-a0bc-11ea-9f05-3469185f1ef1.png)
