### ISSUE TITLE
Set in the Stone the Petal Shape

### ISSUE THREAD

**Issue by Elonex777** [Lithl/challenge32#43]
https://discordapp.com/channels/706675968915406888/707157649308909660/711564687598420071

Keep the more prominent version (current one) or revert the changes or a third option

**Comment by Lithl** [comment]
I am done making changes to the diagram shape. Unless you have someone else take over the project development completely, this decision is made.

**Comment by Elonex777** [comment]
> 
> 
> I am done making changes to the diagram shape. Unless you have someone else take over the project development completely, this decision is made.

I was only speaking of prominent or not since we didn't had the opportunity to talk with Clayman about this, but i understand that you already spent too much time on the shape.
