### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by Lithl** [Lithl/challenge32#6]
There should be a progress bar at the top of the page which indicates how many different color identities have decks set. Identities with multiple decks should only count once.

**Comment by Elonex777** [comment]
Good job @Lithl  it work, the fact that we need to hover mouse to see it might be a bit weird but i guess we could adress this when the whole ui is there like website logo, settings button language icon etc...

**Comment by Lithl** [comment]
004540accf18e626e18b8cceb60a202a76d9f5e3 extends the hover area from 4px to 30px.

The non-hover height is in compliance with Material design, which I am conforming to for the most part.
