### ISSUE TITLE
Allow the user to add additional commanders in the same color identity

### ISSUE THREAD

**Issue by Lithl** [Lithl/challenge32#8]
Players often have multiple decks in a single color identity, even if they're working towards the 32 deck challenge. We should allow them to save a list of additional commanders per identity, though additional commanders won't add to overall progress, per #6

**Comment by Elonex777** [comment]
@Lithl the "alternative commander" don't have a decklist field, if you have several deck of the same color identity you might want to have each decklists.

**Comment by Lithl** [comment]
That was definitely percolating in my mind while designing the layout for this, but I think it slipped my mind during implementation. Could you go create an issue for that so I don't forget? I'm about to catch some sleep.
